import { AnyAction, createAsyncThunk, createSlice, Dispatch } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { fetchCount } from './counterAPI';
import { Contract } from 'starknet';
import contractAbi from './cairo1_abi.json';

export interface CounterState {
  value: number;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: CounterState = {
  value: 0,
  status: 'idle',
};

type AsyncThunkConfig = {
  state: RootState;
  dispatch?: Dispatch<AnyAction>;
  extra?: unknown;
  rejectValue?: unknown;
};

export const fetchBalance = createAsyncThunk<
  {
    contract: Contract; //return value
  },
  void,
  AsyncThunkConfig
>('counter/fetchBalance', async (_, thunkAPI) => {
  console.log('fetching');
  const { provider } = thunkAPI.getState().wallet;

  let contract = null;

  if (provider) {
    // TODO: Get contract address by Network, currently localhost:
    const contractAddress = "0x5ed60a9571c1325b24221a1134ab6ecc957c4f6f4206d1af1bccf3cbc31283f";

    if (contractAddress !== undefined) {
      // const signer = provider.signer;
      // console.log('Signer:', signer);

      // const { abi: contractAbi } = await provider.getClassAt(contractAddress);
      // console.log('Contract ABI:', contractAbi);

      contract = new Contract(
        contractAbi,
        contractAddress,
        provider
      );
      console.log('Contract:', contract);

      // Get balance
      try {
        const balance = await contract.functions.get_balance();
        console.log(balance);

      } catch (error) {
        console.log('Error fetching balance:', error);
        throw error;
      }
    } else {
      throw new Error('No contract address found for this chain');
    }
  } else {
    console.log('No web3 or provider');
    throw new Error('No web3 or provider');
  }

  return {
    contract,
  };
});



// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const incrementAsync = createAsyncThunk(
  'counter/fetchCount',
  async (amount: number) => {
    const response = await fetchCount(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value += action.payload;
      })
      .addCase(incrementAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state: RootState) => state.counter.value;

export default counterSlice.reducer;
